import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Admin-only legacy tokens
        navy: {
          900: "#0A1628",
          800: "#0D1F3C",
          700: "#112951",
        },
        brand: {
          orange: "#E85D1A",
          "orange-hover": "#CF4E0F",
        },
        // Design system tokens — updated palette
        "surface-variant":            "#E3DAD0",
        "secondary":                  "#78716C",
        "on-primary":                 "#FFFFFF",
        "on-secondary":               "#FFFFFF",
        "outline-variant":            "#D5CCB9",
        "primary":                    "#9A4A15",
        "error-container":            "#ffdad6",
        "surface-container-low":      "#F3EDE3",
        "surface-container-highest":  "#E3DAD0",
        "surface-container-lowest":   "#FDFAF5",
        "secondary-container":        "#E8E0D4",
        "on-tertiary-container":      "#454646",
        "surface-bright":             "#F9F5EF",
        "surface":                    "#F7F2EB",
        "tertiary":                   "#706860",
        "on-primary-container":       "#FFFFFF",
        "primary-fixed-dim":          "#D4895A",
        "tertiary-fixed":             "#E3DAD0",
        "tertiary-fixed-dim":         "#C8BFB4",
        "primary-fixed":              "#F5D5B8",
        "surface-container-high":     "#EAE0D4",
        "on-primary-fixed":           "#2B1400",
        "background":                 "#F7F2EB",
        "on-error":                   "#ffffff",
        "primary-container":          "#C8621E",
        "secondary-fixed":            "#C8BFB5",
        "inverse-on-surface":         "#F5EFE8",
        "inverse-surface":            "#111827",
        "on-secondary-fixed":         "#1B1614",
        "surface-container":          "#EDE6DA",
        "on-surface":                 "#1C1917",
        "on-secondary-container":     "#655E59",
        "error":                      "#ba1a1a",
        "surface-dim":                "#D6CFC5",
        "tertiary-container":         "#B5ADA4",
        "outline":                    "#8A7B6E",
        "secondary-fixed-dim":        "#C8C0B7",
        "on-surface-variant":         "#6B6057",
        "surface-tint":               "#9A4A15",
        "on-error-container":         "#93000a",
        "inverse-primary":            "#D4895A",
        "on-background":              "#1C1917",
        "on-tertiary":                "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "96px",
        "gutter": "24px",
      },
      fontFamily: {
        sans:    ["var(--font-dm-sans)"],
        heading: ["var(--font-dm-mono)"],
        display: ["var(--font-barlow)"],
      },
      fontSize: {
        h1:          ["48px",  { lineHeight: "1.05", letterSpacing: "-0.01em", fontWeight: "700" }],
        h2:          ["36px",  { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3:          ["24px",  { lineHeight: "1.3",  fontWeight: "600" }],
        "label-caps":["11px",  { lineHeight: "1",    letterSpacing: "0.12em",  fontWeight: "500" }],
        "body-lg":   ["18px",  { lineHeight: "1.7",  fontWeight: "400" }],
        "body-md":   ["16px",  { lineHeight: "1.7",  fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;
